name: academ_gora
description: App for AcademGora

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: any
  pin_input_text_field: any
  flutter_calendar_carousel: 2.0.1
  expandable: ^4.1.4
  expand_tap_area: any
  cloud_firestore: any
  rxdart: any
  quiver: any
  firebase_database: any
  shared_preferences: any
  firebase_auth_ui: any
  firebase_auth: any
  firebase_core: any
  collection: any
  url_launcher: any
  flutter_phone_direct_caller: any


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/main/
    - assets/auth/
    - assets/registration_to_instructor/
    - assets/instructors_list/
    - assets/registration_parameters/
    - assets/reg_final/
    - assets/account/
    - assets/all_instructors/
    - assets/instructor_profile/
    - assets/instructor_profile/social_network_icons/
    - assets/info_screens/
    - assets/info_screens/call_us/
    - assets/info_screens/prices/
    - assets/info_screens/about_us/
    - assets/info_screens/chill_zone/
    - assets/instructor_set_time/

